# Lab | Data Cleaning and Formatting

In this lab, we will be working with the customer data from an insurance company, which can be found in the CSV file located at the following link: https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv

# Challenge 1: Data Cleaning and Formatting

## Exercise 1: Cleaning Column Names

To ensure consistency and ease of use, standardize the column names of the dataframe. Start by taking a first look at the dataframe and identifying any column names that need to be modified. Use appropriate naming conventions and make sure that column names are descriptive and informative.

*Hint*:
- *Column names should be in lower case*
- *White spaces in column names should be replaced by `_`*
- *`st` could be replaced for `state`*

In [206]:
# Your code here
import pandas as pd
url ="https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv"
insurance_data = pd.read_csv(url)

insurance_data.columns = (insurance_data.columns.str.strip().str.lower().str.replace(" ", "_"))
insurance_data = insurance_data.rename(columns={"st": "state"})
insurance_data.head(20)

,customer,state,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59%,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17%,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,764586.18%,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,536307.65%,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323
5,OC83172,Oregon,F,Bachelor,825629.78%,62902.0,69.0,1/0/00,Personal Auto,Two-Door Car,159.383042
6,XZ87318,Oregon,F,College,538089.86%,55350.0,67.0,1/0/00,Corporate Auto,Four-Door Car,321.600000
7,CF85061,Arizona,M,Master,721610.03%,0.0,101.0,1/0/00,Corporate Auto,Four-Door Car,363.029680
8,DY87989,Oregon,M,Bachelor,2412750.40%,14072.0,71.0,1/0/00,Corporate Auto,Four-Door Car,511.200000
9,BQ94931,Oregon,F,College,738817.81%,28812.0,93.0,1/0/00,Special Auto,Four-Door Car,425.527834
10,SX51350,California,M,College,473899.20%,0.0,67.0,1/0/00,Personal Auto,Four-Door Car,482.400000
11,VQ65197,California,NaN,College,819719.71%,0.0,110.0,1/0/00,Personal Auto,SUV,528.000000
12,DP39365,California,NaN,Master,879879.70%,77026.0,110.0,1/2/00,Corporate Auto,Four-Door Car,472.029737
13,SJ95423,Arizona,NaN,High School or Below,881901.89%,99845.0,110.0,1/1/00,Corporate Auto,SUV,528.000000
14,IL66569,California,NaN,College,538443.17%,83689.0,70.0,1/2/00,Corporate Auto,Four-Door Car,307.139132
15,BW63560,Oregon,NaN,Bachelor,746313.94%,24599.0,64.0,1/1/00,Corporate Auto,Four-Door Car,42.920271
16,FV94802,Nevada,NaN,High School or Below,256686.78%,25049.0,67.0,1/0/00,Personal Auto,Two-Door Car,454.245098
17,OE15005,Cali,NaN,College,394524.16%,28855.0,101.0,1/0/00,Personal Auto,SUV,647.442031
18,WC83389,Oregon,NaN,College,571033.31%,51148.0,72.0,1/0/00,Personal Auto,Four-Door Car,308.981664
19,FL50705,California,NaN,High School or Below,816261.71%,66140.0,101.0,1/0/00,Corporate Auto,Four-Door Car,484.800000

## Exercise 2: Cleaning invalid Values

The dataset contains columns with inconsistent and incorrect values that could affect the accuracy of our analysis. Therefore, we need to clean these columns to ensure that they only contain valid data.

Note that this exercise will focus only on cleaning inconsistent values and will not involve handling null values (NaN or None).

*Hint*:
- *Gender column contains various inconsistent values such as "F", "M", "Femal", "Male", "female", which need to be standardized, for example, to "M" and "F".*
- *State abbreviations be can replaced with its full name, for example "AZ": "Arizona", "Cali": "California", "WA": "Washington"*
- *In education, "Bachelors" could be replaced by "Bachelor"*
- *In Customer Lifetime Value, delete the `%` character*
- *In vehicle class, "Sports Car", "Luxury SUV" and "Luxury Car" could be replaced by "Luxury"*

In [207]:
print(insurance_data.dtypes)

print(insurance_data["state"].value_counts()) # some values seems similar AZ/ Arizona ; WA/Washington ; Cali/california
print(insurance_data["gender"].value_counts()) # Some values are similar F/female/Femal ; Male/M
print(insurance_data["education"].value_counts()) # Some values are similar Bachelor/Bachelors
print(insurance_data["vehicle_class"].value_counts()) # Some values are similar Bachelor/Bachelors

customer                      object
state                         object
gender                        object
education                     object
customer_lifetime_value       object
income                       float64
monthly_premium_auto         float64
number_of_open_complaints     object
policy_type                   object
vehicle_class                 object
total_claim_amount           float64
dtype: object
state
Oregon        320
California    211
Arizona       186
Cali          120
Nevada         98
Washington     81
WA             30
AZ             25
Name: count, dtype: int64
gender
F         457
M         413
Male       39
female     28
Femal      17
Name: count, dtype: int64
education
Bachelor                324
College                 313
High School or Below    296
Master                   94
Doctor                   37
Bachelors                 7
Name: count, dtype: int64
vehicle_class
Four-Door Car    576
Two-Door Car     205
SUV              199
Sports Car        57
Luxury SUV        20
Luxury Car        14
Name: count, dtype: int64

In [208]:


gender_map={"F":"F", "M":"M", "Femal":"F", "Male":"M", "female":"F"}
state_map={"Oregon":"Oregon",
           "California":"California",
           "Arizona":"Arizona",
           "Cali":"California",
           "Nevada":"Nevada",
           "Washington":"Washington",
           "WA":"Washington",
"AZ":"Arizona"}
education_map={"Bachelors":"Bachelor","Bachelor":"Bachelor","College":"College","High School or Below":"High School or Below","Master":"Master","Doctor":"Doctor"}

vehicle_map= {"Sports Car":"Luxury", "Luxury SUV":"Luxury", "Luxury Car":"Luxury","Four-Door Car":"Four-Door Car","Two-Door Car":"Two-Door Car","SUV":"SUV"}
insurance_data["gender"]=insurance_data["gender"].map(gender_map)
insurance_data["state"]=insurance_data["state"].map(state_map)
insurance_data["education"]=insurance_data["education"].map(education_map)
insurance_data["customer_lifetime_value"] = (insurance_data["customer_lifetime_value"].str.replace("%", "", regex=False))
insurance_data["vehicle_class"]=insurance_data["vehicle_class"].map(vehicle_map)
insurance_data.head(20)

,customer,state,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,764586.18,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,536307.65,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323
5,OC83172,Oregon,F,Bachelor,825629.78,62902.0,69.0,1/0/00,Personal Auto,Two-Door Car,159.383042
6,XZ87318,Oregon,F,College,538089.86,55350.0,67.0,1/0/00,Corporate Auto,Four-Door Car,321.600000
7,CF85061,Arizona,M,Master,721610.03,0.0,101.0,1/0/00,Corporate Auto,Four-Door Car,363.029680
8,DY87989,Oregon,M,Bachelor,2412750.40,14072.0,71.0,1/0/00,Corporate Auto,Four-Door Car,511.200000
9,BQ94931,Oregon,F,College,738817.81,28812.0,93.0,1/0/00,Special Auto,Four-Door Car,425.527834
10,SX51350,California,M,College,473899.20,0.0,67.0,1/0/00,Personal Auto,Four-Door Car,482.400000
11,VQ65197,California,NaN,College,819719.71,0.0,110.0,1/0/00,Personal Auto,SUV,528.000000
12,DP39365,California,NaN,Master,879879.70,77026.0,110.0,1/2/00,Corporate Auto,Four-Door Car,472.029737
13,SJ95423,Arizona,NaN,High School or Below,881901.89,99845.0,110.0,1/1/00,Corporate Auto,SUV,528.000000
14,IL66569,California,NaN,College,538443.17,83689.0,70.0,1/2/00,Corporate Auto,Four-Door Car,307.139132
15,BW63560,Oregon,NaN,Bachelor,746313.94,24599.0,64.0,1/1/00,Corporate Auto,Four-Door Car,42.920271
16,FV94802,Nevada,NaN,High School or Below,256686.78,25049.0,67.0,1/0/00,Personal Auto,Two-Door Car,454.245098
17,OE15005,California,NaN,College,394524.16,28855.0,101.0,1/0/00,Personal Auto,SUV,647.442031
18,WC83389,Oregon,NaN,College,571033.31,51148.0,72.0,1/0/00,Personal Auto,Four-Door Car,308.981664
19,FL50705,California,NaN,High School or Below,816261.71,66140.0,101.0,1/0/00,Corporate Auto,Four-Door Car,484.800000

## Exercise 3: Formatting data types

The data types of many columns in the dataset appear to be incorrect. This could impact the accuracy of our analysis. To ensure accurate analysis, we need to correct the data types of these columns. Please update the data types of the columns as appropriate.

It is important to note that this exercise does not involve handling null values (NaN or None).

*Hint*:
- *Customer lifetime value should be numeric*
- *Number of open complaints has an incorrect format. Look at the different values it takes with `unique()` and take the middle value. As an example, 1/5/00 should be 5. Number of open complaints is a string - remember you can use `split()` to deal with it and take the number you need. Finally, since it should be numeric, cast the column to be in its proper type.*

In [209]:
insurance_data["customer_lifetime_value"]=insurance_data["customer_lifetime_value"].astype(float)
print(insurance_data["number_of_open_complaints"].unique())
insurance_data["number_of_open_complaints"]=insurance_data["number_of_open_complaints"].str.split("/").str[1]
insurance_data["number_of_open_complaints"]=insurance_data["number_of_open_complaints"].astype(float)
insurance_data.dtypes

['1/0/00' '1/2/00' '1/1/00' '1/3/00' '1/5/00' '1/4/00' nan]

customer                      object
state                         object
gender                        object
education                     object
customer_lifetime_value      float64
income                       float64
monthly_premium_auto         float64
number_of_open_complaints    float64
policy_type                   object
vehicle_class                 object
total_claim_amount           float64
dtype: object

## Exercise 4: Dealing with Null values

Identify any columns with null or missing values. Identify how many null values each column has. You can use the `isnull()` function in pandas to find columns with null values.

Decide on a strategy for handling the null values. There are several options, including:

- Drop the rows or columns with null values
- Fill the null values with a specific value (such as the column mean or median for numerical variables, and mode for categorical variables)
- Fill the null values with the previous or next value in the column
- Fill the null values based on a more complex algorithm or model (note: we haven't covered this yet)

Implement your chosen strategy to handle the null values. You can use the `fillna()` function in pandas to fill null values or `dropna()` function to drop null values.

Verify that your strategy has successfully handled the null values. You can use the `isnull()` function again to check if there are still null values in the dataset.

Remember to document your process and explain your reasoning for choosing a particular strategy for handling null values.

After formatting data types, as a last step, convert all the numeric variables to integers.

In [210]:
print(insurance_data.isnull())
print(insurance_data.info())
print(insurance_data.isna().sum())
#there are 1071 filled rows and they are all at the top. if we drop the empty lines it will be clearer.

      customer  state  gender  education  customer_lifetime_value  income  \
0        False  False    True      False                     True   False
1        False  False   False      False                    False   False
2        False  False   False      False                    False   False
3        False  False   False      False                    False   False
4        False  False   False      False                    False   False
...        ...    ...     ...        ...                      ...     ...
4003      True   True    True       True                     True    True
4004      True   True    True       True                     True    True
4005      True   True    True       True                     True    True
4006      True   True    True       True                     True    True
4007      True   True    True       True                     True    True

      monthly_premium_auto  number_of_open_complaints  policy_type  \
0                    False                      False        False
1                    False                      False        False
2                    False                      False        False
3                    False                      False        False
4                    False                      False        False
...                    ...                        ...          ...
4003                  True                       True         True
4004                  True                       True         True
4005                  True                       True         True
4006                  True                       True         True
4007                  True                       True         True

      vehicle_class  total_claim_amount
0             False               False
1             False               False
2             False               False
3             False               False
4             False               False
...             ...                 ...
4003           True                True
4004           True                True
4005           True                True
4006           True                True
4007           True                True

[4008 rows x 11 columns]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4008 entries, 0 to 4007
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   customer                   1071 non-null   object
 1   state                      1071 non-null   object
 2   gender                     954 non-null    object
 3   education                  1071 non-null   object
 4   customer_lifetime_value    1068 non-null   float64
 5   income                     1071 non-null   float64
 6   monthly_premium_auto       1071 non-null   float64
 7   number_of_open_complaints  1071 non-null   float64
 8   policy_type                1071 non-null   object
 9   vehicle_class              1071 non-null   object
 10  total_claim_amount         1071 non-null   float64
dtypes: float64(5), object(6)
memory usage: 344.6+ KB
None
customer                     2937
state                        2937
gender                       3054
education                    2937
customer_lifetime_value      2940
income                       2937
monthly_premium_auto         2937
number_of_open_complaints    2937
policy_type                  2937
vehicle_class                2937
total_claim_amount           2937
dtype: int64

In [211]:
insurance_data=insurance_data.dropna(subset="customer")
print(insurance_data.isnull())
print(insurance_data.info())
print(insurance_data.isna().sum())
#there are already 1071 filled rows. gender and customer_life_value are not totaly filled. I choose to fill the blank for the customer_life_value with the median, and the gender with "unknown"

      customer  state  gender  education  customer_lifetime_value  income  \
0        False  False    True      False                     True   False
1        False  False   False      False                    False   False
2        False  False   False      False                    False   False
3        False  False   False      False                    False   False
4        False  False   False      False                    False   False
...        ...    ...     ...        ...                      ...     ...
1066     False  False   False      False                    False   False
1067     False  False   False      False                    False   False
1068     False  False   False      False                    False   False
1069     False  False   False      False                    False   False
1070     False  False   False      False                    False   False

      monthly_premium_auto  number_of_open_complaints  policy_type  \
0                    False                      False        False
1                    False                      False        False
2                    False                      False        False
3                    False                      False        False
4                    False                      False        False
...                    ...                        ...          ...
1066                 False                      False        False
1067                 False                      False        False
1068                 False                      False        False
1069                 False                      False        False
1070                 False                      False        False

      vehicle_class  total_claim_amount
0             False               False
1             False               False
2             False               False
3             False               False
4             False               False
...             ...                 ...
1066          False               False
1067          False               False
1068          False               False
1069          False               False
1070          False               False

[1071 rows x 11 columns]
<class 'pandas.core.frame.DataFrame'>
Index: 1071 entries, 0 to 1070
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   customer                   1071 non-null   object
 1   state                      1071 non-null   object
 2   gender                     954 non-null    object
 3   education                  1071 non-null   object
 4   customer_lifetime_value    1068 non-null   float64
 5   income                     1071 non-null   float64
 6   monthly_premium_auto       1071 non-null   float64
 7   number_of_open_complaints  1071 non-null   float64
 8   policy_type                1071 non-null   object
 9   vehicle_class              1071 non-null   object
 10  total_claim_amount         1071 non-null   float64
dtypes: float64(5), object(6)
memory usage: 100.4+ KB
None
customer                       0
state                          0
gender                       117
education                      0
customer_lifetime_value        3
income                         0
monthly_premium_auto           0
number_of_open_complaints      0
policy_type                    0
vehicle_class                  0
total_claim_amount             0
dtype: int64

In [212]:
median_customer_lifetime_value=insurance_data["customer_lifetime_value"].median()
insurance_data["customer_lifetime_value"]=insurance_data["customer_lifetime_value"].fillna(median_customer_lifetime_value)
insurance_data["gender"]=insurance_data["gender"].fillna("Unknown")
print(insurance_data.isnull())
print(insurance_data.info())
print(insurance_data.isna().sum())
insurance_data.head(20)

      customer  state  gender  education  customer_lifetime_value  income  \
0        False  False   False      False                    False   False
1        False  False   False      False                    False   False
2        False  False   False      False                    False   False
3        False  False   False      False                    False   False
4        False  False   False      False                    False   False
...        ...    ...     ...        ...                      ...     ...
1066     False  False   False      False                    False   False
1067     False  False   False      False                    False   False
1068     False  False   False      False                    False   False
1069     False  False   False      False                    False   False
1070     False  False   False      False                    False   False

      monthly_premium_auto  number_of_open_complaints  policy_type  \
0                    False                      False        False
1                    False                      False        False
2                    False                      False        False
3                    False                      False        False
4                    False                      False        False
...                    ...                        ...          ...
1066                 False                      False        False
1067                 False                      False        False
1068                 False                      False        False
1069                 False                      False        False
1070                 False                      False        False

      vehicle_class  total_claim_amount
0             False               False
1             False               False
2             False               False
3             False               False
4             False               False
...             ...                 ...
1066          False               False
1067          False               False
1068          False               False
1069          False               False
1070          False               False

[1071 rows x 11 columns]
<class 'pandas.core.frame.DataFrame'>
Index: 1071 entries, 0 to 1070
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   customer                   1071 non-null   object
 1   state                      1071 non-null   object
 2   gender                     1071 non-null   object
 3   education                  1071 non-null   object
 4   customer_lifetime_value    1071 non-null   float64
 5   income                     1071 non-null   float64
 6   monthly_premium_auto       1071 non-null   float64
 7   number_of_open_complaints  1071 non-null   float64
 8   policy_type                1071 non-null   object
 9   vehicle_class              1071 non-null   object
 10  total_claim_amount         1071 non-null   float64
dtypes: float64(5), object(6)
memory usage: 100.4+ KB
None
customer                     0
state                        0
gender                       0
education                    0
customer_lifetime_value      0
income                       0
monthly_premium_auto         0
number_of_open_complaints    0
policy_type                  0
vehicle_class                0
total_claim_amount           0
dtype: int64

,customer,state,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount
0,RB50392,Washington,Unknown,Master,588174.235,0.0,1000.0,0.0,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.590,0.0,94.0,0.0,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.170,48767.0,108.0,0.0,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,764586.180,0.0,106.0,0.0,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,536307.650,36357.0,68.0,0.0,Personal Auto,Four-Door Car,17.269323
5,OC83172,Oregon,F,Bachelor,825629.780,62902.0,69.0,0.0,Personal Auto,Two-Door Car,159.383042
6,XZ87318,Oregon,F,College,538089.860,55350.0,67.0,0.0,Corporate Auto,Four-Door Car,321.600000
7,CF85061,Arizona,M,Master,721610.030,0.0,101.0,0.0,Corporate Auto,Four-Door Car,363.029680
8,DY87989,Oregon,M,Bachelor,2412750.400,14072.0,71.0,0.0,Corporate Auto,Four-Door Car,511.200000
9,BQ94931,Oregon,F,College,738817.810,28812.0,93.0,0.0,Special Auto,Four-Door Car,425.527834
10,SX51350,California,M,College,473899.200,0.0,67.0,0.0,Personal Auto,Four-Door Car,482.400000
11,VQ65197,California,Unknown,College,819719.710,0.0,110.0,0.0,Personal Auto,SUV,528.000000
12,DP39365,California,Unknown,Master,879879.700,77026.0,110.0,2.0,Corporate Auto,Four-Door Car,472.029737
13,SJ95423,Arizona,Unknown,High School or Below,881901.890,99845.0,110.0,1.0,Corporate Auto,SUV,528.000000
14,IL66569,California,Unknown,College,538443.170,83689.0,70.0,2.0,Corporate Auto,Four-Door Car,307.139132
15,BW63560,Oregon,Unknown,Bachelor,746313.940,24599.0,64.0,1.0,Corporate Auto,Four-Door Car,42.920271
16,FV94802,Nevada,Unknown,High School or Below,256686.780,25049.0,67.0,0.0,Personal Auto,Two-Door Car,454.245098
17,OE15005,California,Unknown,College,394524.160,28855.0,101.0,0.0,Personal Auto,SUV,647.442031
18,WC83389,Oregon,Unknown,College,571033.310,51148.0,72.0,0.0,Personal Auto,Four-Door Car,308.981664
19,FL50705,California,Unknown,High School or Below,816261.710,66140.0,101.0,0.0,Corporate Auto,Four-Door Car,484.800000

## Exercise 5: Dealing with duplicates

Use the `.duplicated()` method to identify any duplicate rows in the dataframe.

Decide on a strategy for handling the duplicates. Options include:
- Dropping all duplicate rows
- Keeping only the first occurrence of each duplicated row
- Keeping only the last occurrence of each duplicated row
- Dropping duplicates based on a subset of columns
- Dropping duplicates based on a specific column

Implement your chosen strategy using the `drop_duplicates()` function.

Verify that your strategy has successfully handled the duplicates by checking for duplicates again using `.duplicated()`.

Remember to document your process and explain your reasoning for choosing a particular strategy for handling duplicates.

Save the cleaned dataset to a new CSV file.

*Hint*: *after dropping duplicates, reset the index to ensure consistency*.

In [215]:
dupl = insurance_data.duplicated()
print("Number of duplicated rows:", dupl.sum())
insurance_data_no_duplicates = insurance_data.drop_duplicates(subset=["customer"],keep="first")

print("Rows before:", len(insurance_data))
print("Rows after:", len(insurance_data_no_duplicates))
#It seems there is no duplicate

Number of duplicated rows: 0
Rows before: 1071
Rows after: 1071

# Bonus: Challenge 2: creating functions on a separate `py` file

Put all the data cleaning and formatting steps into functions, and create a main function that performs all the cleaning and formatting.

Write these functions in separate .py file(s). By putting these steps into functions, we can make the code more modular and easier to maintain.

*Hint: autoreload module is a utility module in Python that allows you to automatically reload modules in the current session when changes are made to the source code. This can be useful in situations where you are actively developing code and want to see the effects of changes you make without having to constantly restart the Python interpreter or Jupyter Notebook kernel.*

In [217]:
%load_ext autoreload
%autoreload 2 
from EX1 import ex1_load_data
from EX2 import ex2_clean_categorical
from EX3 import ex3_fix_types
from EX4 import ex4_handle_missing
from EX5 import ex5_remove_duplicates

insurance_data = ex1_load_data()
insurance_data = ex2_clean_categorical(insurance_data)
insurance_data = ex3_fix_types(insurance_data)
insurance_data = ex4_handle_missing(insurance_data)
insurance_data = ex5_remove_duplicates(insurance_data)

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
customer                      object
state                         object
gender                        object
education                     object
customer_lifetime_value       object
income                       float64
monthly_premium_auto         float64
number_of_open_complaints     object
policy_type                   object
vehicle_class                 object
total_claim_amount           float64
dtype: object
state
Oregon        320
California    211
Arizona       186
Cali          120
Nevada         98
Washington     81
WA             30
AZ             25
Name: count, dtype: int64
gender
F         457
M         413
Male       39
female     28
Femal      17
Name: count, dtype: int64
education
Bachelor                324
College                 313
High School or Below    296
Master                   94
Doctor                   37
Bachelors                 7
Name: count, dtype: int64
vehicle_class
Four-Door Car    576
Two-Door Car     205
SUV              199
Sports Car        57
Luxury SUV        20
Luxury Car        14
Name: count, dtype: int64
['1/0/00' '1/2/00' '1/1/00' '1/3/00' '1/5/00' '1/4/00' nan]
customer                      object
state                         object
gender                        object
education                     object
customer_lifetime_value      float64
income                       float64
monthly_premium_auto         float64
number_of_open_complaints    float64
policy_type                   object
vehicle_class                 object
total_claim_amount           float64
dtype: object
      customer  state  gender  education  customer_lifetime_value  income  \
0        False  False    True      False                     True   False
1        False  False   False      False                    False   False
2        False  False   False      False                    False   False
3        False  False   False      False                    False   False
4        False  False   False      False                    False   False
...        ...    ...     ...        ...                      ...     ...
4003      True   True    True       True                     True    True
4004      True   True    True       True                     True    True
4005      True   True    True       True                     True    True
4006      True   True    True       True                     True    True
4007      True   True    True       True                     True    True

      monthly_premium_auto  number_of_open_complaints  policy_type  \
0                    False                      False        False
1                    False                      False        False
2                    False                      False        False
3                    False                      False        False
4                    False                      False        False
...                    ...                        ...          ...
4003                  True                       True         True
4004                  True                       True         True
4005                  True                       True         True
4006                  True                       True         True
4007                  True                       True         True

      vehicle_class  total_claim_amount
0             False               False
1             False               False
2             False               False
3             False               False
4             False               False
...             ...                 ...
4003           True                True
4004           True                True
4005           True                True
4006           True                True
4007           True                True

[4008 rows x 11 columns]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4008 entries, 0 to 4007
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   customer                   1071 non-null   object
 1   state                      1071 non-null   object
 2   gender                     954 non-null    object
 3   education                  1071 non-null   object
 4   customer_lifetime_value    1068 non-null   float64
 5   income                     1071 non-null   float64
 6   monthly_premium_auto       1071 non-null   float64
 7   number_of_open_complaints  1071 non-null   float64
 8   policy_type                1071 non-null   object
 9   vehicle_class              1071 non-null   object
 10  total_claim_amount         1071 non-null   float64
dtypes: float64(5), object(6)
memory usage: 344.6+ KB
None
customer                     2937
state                        2937
gender                       3054
education                    2937
customer_lifetime_value      2940
income                       2937
monthly_premium_auto         2937
number_of_open_complaints    2937
policy_type                  2937
vehicle_class                2937
total_claim_amount           2937
dtype: int64
      customer  state  gender  education  customer_lifetime_value  income  \
0        False  False    True      False                     True   False
1        False  False   False      False                    False   False
2        False  False   False      False                    False   False
3        False  False   False      False                    False   False
4        False  False   False      False                    False   False
...        ...    ...     ...        ...                      ...     ...
1066     False  False   False      False                    False   False
1067     False  False   False      False                    False   False
1068     False  False   False      False                    False   False
1069     False  False   False      False                    False   False
1070     False  False   False      False                    False   False

      monthly_premium_auto  number_of_open_complaints  policy_type  \
0                    False                      False        False
1                    False                      False        False
2                    False                      False        False
3                    False                      False        False
4                    False                      False        False
...                    ...                        ...          ...
1066                 False                      False        False
1067                 False                      False        False
1068                 False                      False        False
1069                 False                      False        False
1070                 False                      False        False

      vehicle_class  total_claim_amount
0             False               False
1             False               False
2             False               False
3             False               False
4             False               False
...             ...                 ...
1066          False               False
1067          False               False
1068          False               False
1069          False               False
1070          False               False

[1071 rows x 11 columns]
<class 'pandas.core.frame.DataFrame'>
Index: 1071 entries, 0 to 1070
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   customer                   1071 non-null   object
 1   state                      1071 non-null   object
 2   gender                     954 non-null    object
 3   education                  1071 non-null   object
 4   customer_lifetime_value    1068 non-null   float64
 5   income                     1071 non-null   float64
 6   monthly_premium_auto       1071 non-null   float64
 7   number_of_open_complaints  1071 non-null   float64
 8   policy_type                1071 non-null   object
 9   vehicle_class              1071 non-null   object
 10  total_claim_amount         1071 non-null   float64
dtypes: float64(5), object(6)
memory usage: 100.4+ KB
None
customer                       0
state                          0
gender                       117
education                      0
customer_lifetime_value        3
income                         0
monthly_premium_auto           0
number_of_open_complaints      0
policy_type                    0
vehicle_class                  0
total_claim_amount             0
dtype: int64
      customer  state  gender  education  customer_lifetime_value  income  \
0        False  False   False      False                    False   False
1        False  False   False      False                    False   False
2        False  False   False      False                    False   False
3        False  False   False      False                    False   False
4        False  False   False      False                    False   False
...        ...    ...     ...        ...                      ...     ...
1066     False  False   False      False                    False   False
1067     False  False   False      False                    False   False
1068     False  False   False      False                    False   False
1069     False  False   False      False                    False   False
1070     False  False   False      False                    False   False

      monthly_premium_auto  number_of_open_complaints  policy_type  \
0                    False                      False        False
1                    False                      False        False
2                    False                      False        False
3                    False                      False        False
4                    False                      False        False
...                    ...                        ...          ...
1066                 False                      False        False
1067                 False                      False        False
1068                 False                      False        False
1069                 False                      False        False
1070                 False                      False        False

      vehicle_class  total_claim_amount
0             False               False
1             False               False
2             False               False
3             False               False
4             False               False
...             ...                 ...
1066          False               False
1067          False               False
1068          False               False
1069          False               False
1070          False               False

[1071 rows x 11 columns]
<class 'pandas.core.frame.DataFrame'>
Index: 1071 entries, 0 to 1070
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   customer                   1071 non-null   object
 1   state                      1071 non-null   object
 2   gender                     1071 non-null   object
 3   education                  1071 non-null   object
 4   customer_lifetime_value    1071 non-null   float64
 5   income                     1071 non-null   float64
 6   monthly_premium_auto       1071 non-null   float64
 7   number_of_open_complaints  1071 non-null   float64
 8   policy_type                1071 non-null   object
 9   vehicle_class              1071 non-null   object
 10  total_claim_amount         1071 non-null   float64
dtypes: float64(5), object(6)
memory usage: 100.4+ KB
None
customer                     0
state                        0
gender                       0
education                    0
customer_lifetime_value      0
income                       0
monthly_premium_auto         0
number_of_open_complaints    0
policy_type                  0
vehicle_class                0
total_claim_amount           0
dtype: int64
Number of duplicated rows: 0
Rows before: 1071
Rows after: 1071

C:\Users\matth\Ironhack\labs\lab-dw-data-cleaning-and-formatting\EX4.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  insurance_data["customer_lifetime_value"]=insurance_data["customer_lifetime_value"].fillna(median_customer_lifetime_value)
C:\Users\matth\Ironhack\labs\lab-dw-data-cleaning-and-formatting\EX4.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  insurance_data["gender"]=insurance_data["gender"].fillna("Unknown")

# Bonus: Challenge 3: Analyzing Clean and Formated Data

You have been tasked with analyzing the data to identify potential areas for improving customer retention and profitability. Your goal is to identify customers with a high policy claim amount and a low customer lifetime value.

In the Pandas Lab, we only looked at high policy claim amounts because we couldn't look into low customer lifetime values. If we had tried to work with that column, we wouldn't have been able to because customer lifetime value wasn't clean and in its proper format. So after cleaning and formatting the data, let's get some more interesting insights!

Instructions:

- Review the statistics again for total claim amount and customer lifetime value to gain an understanding of the data.
- To identify potential areas for improving customer retention and profitability, we want to focus on customers with a high policy claim amount and a low customer lifetime value. Consider customers with a high policy claim amount to be those in the top 25% of the total claim amount, and clients with a low customer lifetime value to be those in the bottom 25% of the customer lifetime value. Create a pandas DataFrame object that contains information about customers with a policy claim amount greater than the 75th percentile and a customer lifetime value in the bottom 25th percentile.
- Use DataFrame methods to calculate summary statistics about the high policy claim amount and low customer lifetime value data. To do so, select both columns of the dataframe simultaneously and pass it to the `.describe()` method. This will give you descriptive statistics, such as mean, median, standard deviation, minimum and maximum values for both columns at the same time, allowing you to compare and analyze their characteristics.

In [222]:
insurance_data[["customer_lifetime_value","total_claim_amount"]].describe()

high_percentile_claimed=insurance_data["total_claim_amount"].quantile(0.75)
low_percentile_lifetime=insurance_data["customer_lifetime_value"].quantile(0.25)
main_target=insurance_data.loc[(insurance_data["total_claim_amount"]>high_percentile_claimed)&(insurance_data["customer_lifetime_value"]<low_percentile_lifetime)]
print(main_target)
main_target[["customer_lifetime_value","total_claim_amount"]].describe()

     customer       state   gender             education  \
17    OE15005  California  Unknown               College
23    TZ98966      Nevada  Unknown              Bachelor
26    US89481  California  Unknown              Bachelor
38    CM61827      Oregon  Unknown              Bachelor
42    IL19217  California  Unknown              Bachelor
62    FG63582      Oregon  Unknown              Bachelor
135   MS41162     Arizona  Unknown  High School or Below
140   DS81757      Oregon        M               College
158   KA61892     Arizona        M               College
160   ND87334  California        M  High School or Below
170   TS19868  California        M               College
184   AB13432  California        M              Bachelor
204   FL34139  California        M  High School or Below
250   IA63417     Arizona        F  High School or Below
269   VZ51506     Arizona        F  High School or Below
279   OH60605      Oregon        F  High School or Below
304   RR77985      Oregon        F              Bachelor
388   JF36291  California        M               College
415   ZF84449      Oregon        F               College
448   NL93182      Nevada        M              Bachelor
450   WE68644      Oregon        F              Bachelor
467   AU96286      Oregon        F              Bachelor
486   FY51713     Arizona        F              Bachelor
500   XN11823      Nevada        F              Bachelor
502   PX17116      Nevada        M               College
565   XS12556  California        F               College
590   UK41984     Arizona        F                Doctor
593   ZK21724      Oregon        F  High School or Below
638   DM95829  California        M               College
645   JA41698      Nevada        M              Bachelor
669   ED50963  California        F  High School or Below
709   NZ15548      Oregon        M              Bachelor
788   TE13577      Oregon        F               College
853   TV25678  Washington        M               College
891   KJ87930  California        F              Bachelor
908   XM72420     Arizona        F  High School or Below
949   TD10493      Oregon        F  High School or Below
1019  OT52034  California        M              Bachelor
1022  UI73201  California        M               College
1068  GS98873     Arizona        F              Bachelor

      customer_lifetime_value   income  monthly_premium_auto  \
17                  394524.16  28855.0                 101.0
23                  245019.10      0.0                  73.0
26                  394637.21      0.0                 111.0
38                  309003.41      0.0                  90.0
42                  393900.64  60021.0                  99.0
62                  333976.49      0.0                  94.0
135                 402296.35      0.0                 117.0
140                 247012.12      0.0                  74.0
158                 387364.70  28142.0                 105.0
160                 228759.69      0.0                  63.0
170                 241313.97  27501.0                  63.0
184                 373583.81      0.0                 110.0
204                 368811.09      0.0                  63.0
250                 400151.91  19782.0                 108.0
269                 359531.29      0.0                 103.0
279                 365253.24  39679.0                  92.0
304                 288774.23      0.0                  80.0
388                 387364.70  28142.0                 105.0
415                 372672.80      0.0                 112.0
448                 254945.00      0.0                  78.0
450                 380392.18  20325.0                 100.0
467                 316765.84      0.0                  92.0
486                 357076.05  56168.0                  88.0
500                 376446.51  92600.0                  94.0
502                 362345.42      0.0                 111.0
565                 368309.99      0.0                 101.0
590                 383960.61      0.0                 112.0
593                 401654.20      0.0                 111.0
638                 252395.96  16244.0                  68.0
645                 309953.80      0.0                 102.0
669                 268886.40  32808.0                  68.0
709                 402381.44  41833.0                 103.0
788                 231973.59      0.0                  64.0
853                 354090.43      0.0                 101.0
891                 388650.48      0.0                 112.0
908                 391936.67  66676.0                  97.0
949                 289873.27      0.0                  96.0
1019                386477.68  24204.0                  99.0
1022                366737.50  62375.0                  92.0
1068                323912.47  16061.0                  88.0

      number_of_open_complaints     policy_type  vehicle_class  \
17                          0.0   Personal Auto            SUV
23                          3.0  Corporate Auto  Four-Door Car
26                          0.0   Personal Auto  Four-Door Car
38                          0.0   Personal Auto   Two-Door Car
42                          0.0   Personal Auto  Four-Door Car
62                          0.0   Personal Auto   Two-Door Car
135                         0.0   Personal Auto            SUV
140                         0.0   Personal Auto   Two-Door Car
158                         0.0   Personal Auto         Luxury
160                         0.0  Corporate Auto   Two-Door Car
170                         0.0   Personal Auto  Four-Door Car
184                         0.0   Personal Auto            SUV
204                         3.0   Personal Auto  Four-Door Car
250                         0.0   Personal Auto   Two-Door Car
269                         0.0  Corporate Auto         Luxury
279                         0.0   Personal Auto   Two-Door Car
304                         0.0   Personal Auto  Four-Door Car
388                         0.0   Personal Auto         Luxury
415                         1.0    Special Auto         Luxury
448                         0.0  Corporate Auto  Four-Door Car
450                         0.0   Personal Auto         Luxury
467                         0.0  Corporate Auto  Four-Door Car
486                         0.0   Personal Auto  Four-Door Car
500                         0.0  Corporate Auto   Two-Door Car
502                         2.0  Corporate Auto            SUV
565                         0.0  Corporate Auto         Luxury
590                         2.0   Personal Auto            SUV
593                         0.0   Personal Auto            SUV
638                         0.0   Personal Auto   Two-Door Car
645                         5.0  Corporate Auto            SUV
669                         1.0   Personal Auto  Four-Door Car
709                         0.0   Personal Auto  Four-Door Car
788                         0.0   Personal Auto  Four-Door Car
853                         0.0   Personal Auto            SUV
891                         0.0  Corporate Auto            SUV
908                         0.0   Personal Auto  Four-Door Car
949                         4.0   Personal Auto  Four-Door Car
1019                        1.0   Personal Auto  Four-Door Car
1022                        0.0   Personal Auto   Two-Door Car
1068                        0.0   Personal Auto  Four-Door Car

      total_claim_amount
17            647.442031
23            554.376763
26            799.200000
38            648.000000
42            882.871945
62            863.327324
135           975.107098
140           721.242206
158           701.708239
160           679.368378
170           542.319401
184           792.000000
204           669.682001
250           773.470977
269           741.600000
279           641.388616
304           676.944023
388           701.708239
415           806.400000
448           845.654042
450           668.293970
467           662.400000
486           614.675906
500           842.437850
502          1171.931170
565           564.466556
590           537.600000
593           799.200000
638           623.223617
645           862.762957
669           541.695658
709           643.826716
788           632.715382
853           727.200000
891          1185.988301
908           558.099357
949           691.200000
1019          707.303416
1022          618.630955
1068          633.600000

       customer_lifetime_value  total_claim_amount
count                40.000000           40.000000
mean             341577.910000          723.776577
std               56921.472027          149.280606
min              228759.690000          537.600000
25%              304220.875000          633.378846
50%              365995.370000          685.284189
75%              387364.700000          799.200000
max              402381.440000         1185.988301